//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chi_Tiet_Ve
    {
        public long ChiTietVeID { get; set; }
        public Nullable<long> DonDatVeID { get; set; }
        public Nullable<long> LichChieuID { get; set; }
        public Nullable<long> GheID { get; set; }
        public string LoaiGhe { get; set; }
        public string LoaiVe { get; set; }
        public Nullable<bool> TrangThaiSuDung { get; set; }
    
        public virtual Don_Dat_Ve Don_Dat_Ve { get; set; }
        public virtual Ghe_Ngoi Ghe_Ngoi { get; set; }
        public virtual Lich_Chieu Lich_Chieu { get; set; }
        public virtual TienVe TienVe { get; set; }
    }
}
