//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khach_Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khach_Hang()
        {
            this.Don_Dat_Ve = new HashSet<Don_Dat_Ve>();
            this.Khoa_Ghe_Tam_Thoi = new HashSet<Khoa_Ghe_Tam_Thoi>();
        }
    
        public long KhachHangID { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string TenDayDu { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public Nullable<int> DiemThanhVien { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> NgayTaoTaiKhoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Don_Dat_Ve> Don_Dat_Ve { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Khoa_Ghe_Tam_Thoi> Khoa_Ghe_Tam_Thoi { get; set; }
    }
}
