//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LTW_DatVeXemPhimEntities : DbContext
    {
        public LTW_DatVeXemPhimEntities()
            : base("name=LTW_DatVeXemPhimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chi_Tiet_Ve> Chi_Tiet_Ve { get; set; }
        public virtual DbSet<Don_Dat_Ve> Don_Dat_Ve { get; set; }
        public virtual DbSet<Ghe_Ngoi> Ghe_Ngoi { get; set; }
        public virtual DbSet<Khach_Hang> Khach_Hang { get; set; }
        public virtual DbSet<Khoa_Ghe_Tam_Thoi> Khoa_Ghe_Tam_Thoi { get; set; }
        public virtual DbSet<Lich_Chieu> Lich_Chieu { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhomNguoiDung> NhomNguoiDungs { get; set; }
        public virtual DbSet<Phim> Phims { get; set; }
        public virtual DbSet<Phong_Chieu> Phong_Chieu { get; set; }
        public virtual DbSet<Rap_Chieu> Rap_Chieu { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<TienVe> TienVes { get; set; }
    }
}
